apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jobaaa
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: job
            image: octarinesec/echo_server:latest
            command: ["echo"]
            args: ["aaaa"]
          restartPolicy: OnFailure
